#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 10 22:34:59 2020

@author: danpak94
"""

##

import os
import numpy as np
import pyvista as pv
import subprocess
import igl
import torch
import vtk
from pytorch3d.structures import Meshes
from pdb import set_trace

import utils_sp

##

def run_and_print(subprocess_arg, return_output=False):
    result = subprocess.run(subprocess_arg, capture_output=True)
    
    print('Exit code: {}'.format(result.returncode))
    
    if not result.stdout == b'':
        print('Output:\n{}'.format(result.stdout.decode('utf-8')))
        
    if not result.stderr == b'':
        print('Error:\n{}'.format(result.stderr.decode('utf-8')))
    
    if return_output:
        return result.stdout.decode('utf-8')

##

def pv_get_point_id_callback(mesh_pv, point_id):
    if 'RegionId' in mesh_pv.point_arrays.keys():
        print('RegionId: {}'.format(mesh_pv.point_arrays['RegionId'][0]))
    print('Point idx: {}'.format(point_id))

def pv_get_cell_id_callback(cell_id):
    print('Cell idx: {}'.format(cell_id.cell_arrays['original_cell_ids']))

def get_verts_faces_from_pyvista(custom_pv):
    verts = custom_pv.points

    if isinstance(custom_pv, pv.core.pointset.PolyData):
        faces_pv = custom_pv.faces
    elif isinstance(custom_pv, pv.core.pointset.UnstructuredGrid):
        faces_pv = custom_pv.cells

    """ faces_pv is in vtk format
    e.g. [3,100,101,102,4,202,203,204,205] is tri element [100,101,102] and quad element [202,203,204,205]
    """
    faces = []
    is_n_verts = True
    for val in faces_pv:
        if is_n_verts:
            n_verts_remain = val
            face = []
            is_n_verts = False
            continue

        if n_verts_remain > 0:
            face.append(val)
            n_verts_remain -= 1

        if n_verts_remain == 0:
            faces.append(face)
            is_n_verts = True

    n_elem = np.unique(np.array([len(face) for face in faces]))
    if len(n_elem) == 1:
        faces = np.array(faces)

    # if isinstance(custom_pv, pv.core.pointset.PolyData):
    #     faces = custom_pv.faces.reshape(-1, custom_pv.faces[0]+1)[:,1:]
    # elif isinstance(custom_pv, pv.core.pointset.UnstructuredGrid):
    #     faces = custom_pv.cells.reshape(-1, custom_pv.cells[0] + 1)[:, 1:]

    return verts, faces

def write_off_file(filepath, verts, faces, colors=None):
    with open(filepath, 'w') as f:
        f.write('OFF\n')
        f.write('{} {} {}\n\n'.format(verts.shape[0], faces.shape[0], 0))
        
        for vert in verts:
            f.write('{} {} {}\n'.format(vert[0], vert[1], vert[2]))

        for idx, face in enumerate(faces):
            ''' https://stackoverflow.com/questions/2721521/fastest-way-to-generate-delimited-string-from-1d-numpy-array '''
            #generate an array with strings
            if colors is not None:
                face_arrstr = np.char.mod('%i', face)
                color_arrstr = ['%i'% c for c in colors[idx]]
                
                face_arrstr = list(face_arrstr) + list(color_arrstr)
            else:
                face_arrstr = np.char.mod('%i', face)
                
            face_str = " ".join(face_arrstr)
            
            f.write('{} {}\n'.format(len(face), face_str))

def write_inp_file(inp_filepath, verts, elems_list, comp_name_list):
    # **
    # ** ABAQUS Input Deck Generated by HyperMesh Version  : 2019.1.0.20
    # ** Generated using HyperMesh-Abaqus Template Version : 2019.1.0.20
    # **
    # **   Template:  ABAQUS/STANDARD 3D
    # **
    # *NODE
    #      14666,  -12.71998018721,  -2.082900663117,  4.4336241171974
    #
    # **HWCOLOR COMP         13     7
    # *ELEMENT,TYPE=C3D8R,ELSET=aw-solid
    #      24156,     17076,     17142,     17143,     17068,     26400,     26401,     26402,
    #      26403
    # *****
    #

    color_list = ['13     7', '10    21']

    with open(inp_filepath, 'w') as f:
        f.write('**\n')
        f.write("** Generated by Daniel Pak's vtk-to-inp conversion code\n")
        f.write('**\n')
        f.write('**   Template:  ABAQUS/STANDARD 3D\n')
        f.write('**\n')
        f.write('*NODE\n')

        for vert_idx, vert in enumerate(verts):
            f.write('     {},  {},  {},  {}\n'.format(vert_idx+1, vert[0], vert[1], vert[2]))

        start_idx = 0
        for elems, comp_name, color in zip(elems_list, comp_name_list, color_list):
            f.write('**HWCOLOR COMP         {}\n'.format(color))

            if elems.shape[1] == 8:
                elem_type = 'C3D8R'
            elif elems.shape[1] == 4:
                elem_type = 'C3D4'
            else:
                raise NotImplementedError('elems must be linear hex or linear tet')
            f.write('*ELEMENT,TYPE={},ELSET={}\n'.format(elem_type, comp_name))

            for face_idx, elem in enumerate(elems):
                ''' https://stackoverflow.com/questions/2721521/fastest-way-to-generate-delimited-string-from-1d-numpy-array '''
                face_arrstr = np.char.mod('%i', elem+1) # generate an array with strings
                face_str = ",        ".join(face_arrstr) # define delimiter
                f.write('     {},        {}\n'.format(start_idx+face_idx+1, face_str))

            start_idx += face_idx+1
        f.write('*****\n')

def get_clipper_along_points(verts, faces, points, cyclical_clipper=False, return_faces_flipped=False):
    '''
    Note: points will be projected onto mesh surface, so they don't have to reside on the mesh already
    '''
    # get projections of points onto mesh
    _, face_idxes, proj_pts = igl.point_mesh_squared_distance(points, verts, faces)
    # print(proj_pts_old.shape)
    # # remove proj_pts that are too close to each other
    # new_pts, _, _ = igl.remove_duplicates(proj_pts_old,
    #                                       igl.polygon_mesh_to_triangle_mesh(np.arange(proj_pts_old.shape[0])[np.newaxis]),
    #                                       5e-2) # same val as scale for now
    # # get projections of new projc_pts (no duplicates) onto mesh
    # _, face_idxes, proj_pts = igl.point_mesh_squared_distance(new_pts, verts, faces)
    # print(proj_pts.shape)

    scale = 0.05
    if not cyclical_clipper:
        # extending border verts to properly clip (cgal requires clipper to stick out of mesh that we're trying to cut)
        proj_pts[0] = proj_pts[0] + scale*(proj_pts[0]-proj_pts[1])/np.linalg.norm(proj_pts[0]-proj_pts[1])
        proj_pts[-1] = proj_pts[-1] + scale*(proj_pts[-1]-proj_pts[-2])/np.linalg.norm(proj_pts[-1]-proj_pts[-2])

    mesh_pv = utils_sp.mesh_to_pyvista_PolyData(verts, faces)
    proj_pts_offset1 = proj_pts + mesh_pv.cell_normals[face_idxes]*scale
    proj_pts_offset2 = proj_pts - mesh_pv.cell_normals[face_idxes]*scale
    cut_verts = np.concatenate([proj_pts_offset1, proj_pts_offset2])    
    
    cut_faces = [[i, i+1, len(proj_pts)+i+1, len(proj_pts)+i] for i in range(len(proj_pts)-1)]
    
    if cyclical_clipper:
        # filling in gap between last verts and first verts
        cut_faces.append([len(proj_pts)-1, 0, len(proj_pts), len(proj_pts)*2-1])
    
    cut_faces = np.array(cut_faces)

    # cut_verts, cut_faces, _ = igl.remove_duplicates(cut_verts, cut_faces, 1e-2)

    if return_faces_flipped:
        cut_faces_flipped = cut_faces.copy()
        cut_faces_flipped[:,1] = cut_faces[:,3]
        cut_faces_flipped[:,3] = cut_faces[:,1]
        
        cut_faces = igl.polygon_mesh_to_triangle_mesh(cut_faces)
        cut_faces_flipped = igl.polygon_mesh_to_triangle_mesh(cut_faces_flipped)

        return cut_verts, cut_faces, cut_faces_flipped
    else:
        cut_faces = igl.polygon_mesh_to_triangle_mesh(cut_faces)
        return cut_verts, cut_faces

def combine_independent_meshes(verts1, faces1, verts2, faces2, combine_backbone=True):
    '''
    This just combines verts and faces of two meshes that don't intersect at all
    '''
    verts = np.concatenate([verts1, verts2])
    
    faces2 = faces2 + verts1.shape[0]
    faces = np.concatenate([faces1, faces2])
    
    if combine_backbone: # only applicable for clipping between commissures, probably
        pass
        # back_verts1_idx = np.arange(len(verts1)/2, len(verts1))
        # back_verts2_idx = np.arange(len(verts1)/2, len(verts1), -1)
        
        # one_big_face = 
        
        # igl.polygon_mesh_to_triangle_mesh(one_big_face)
    
    # faces = np.append(faces, np.array([[len(verts1)/2, len(verts1)-1, len(verts1)+len(verts2)/2]]), axis=0).astype(int)
    # faces = np.append(faces, np.array([[len(verts1)/2, len(verts1)+len(verts2)/2, len(verts1)+len(verts2)-1]]), axis=0).astype(int)
    
    return verts, faces

def get_border_vert_idxes_in_order(faces, start_idx, reverse=False):
    """
    start_idx: should be a corner vertex idx
    """
    if not reverse:
        init_axis = 1
        step_axis = 0
    else:
        init_axis = 0
        step_axis = 1

    exterior_edges = igl.exterior_edges(faces)

    idx_store = [start_idx]
    curr_idx = start_idx
    n_iter = 0
    next_idx = np.nan

    while (next_idx != start_idx) and n_iter<=1000:
        next_idx = exterior_edges[exterior_edges[:, init_axis] == curr_idx][:, step_axis][0]

        idx_store.append(next_idx)
        curr_idx = next_idx

        n_iter += 1

    if n_iter >= 1000:
        print('get_border_vert_idxes_in_order n_iter >= 1000')

    return np.array(idx_store)

def split_border_vert_idxes_at_corners(border_vert_idxes_ordered, corner_vert_idxes):
    split_idxes = []
    for corner_vert_idx in corner_vert_idxes:
        if (border_vert_idxes_ordered == corner_vert_idx).sum() > 1:
            continue
        else:
            split_idxes.append(np.where(border_vert_idxes_ordered == corner_vert_idx)[0][0])

    output_idxes = []
    idx_begin = 0
    for split_idx in split_idxes:
        output_idxes.append(border_vert_idxes_ordered[idx_begin:split_idx+1])
        idx_begin = split_idx
    output_idxes.append(border_vert_idxes_ordered[idx_begin:])

    return output_idxes

def split_quad_to_2_tri_mesh(faces):
    """ faces is a list of lists that are either tri and quad faces """
    tri_faces = []
    for face in faces:
        if len(face) == 4:
            tri_faces.append([face[0], face[1], face[2]])
            tri_faces.append([face[0], face[2], face[3]])
        else:
            tri_faces.append(face)

    return np.array(tri_faces)

def merge_commissure_verts(leaflet_verts1, leaflet_verts2):
    """
    only works for liang meshes (hardcoded vert indices)
    """
    # left_top5_vert_idxes = [6, 7, 8, 25, 26]
    # right_top5_vert_idxes = [487, 484, 483, 505, 504]

    left_top5_vert_idxes = [1, 251, 3, 260, 4]
    right_top5_vert_idxes = [131, 490, 132, 500, 133]

    leaflet_verts1_new = leaflet_verts1.copy()
    leaflet_verts2_new = leaflet_verts2.copy()

    mean_vert_pos = (leaflet_verts1[right_top5_vert_idxes, :] + leaflet_verts2[left_top5_vert_idxes, :])/2

    leaflet_verts1_new[right_top5_vert_idxes, :] = mean_vert_pos
    leaflet_verts2_new[left_top5_vert_idxes, :] = mean_vert_pos

    return leaflet_verts1_new, leaflet_verts2_new

def make_room_between_leaflet_boundaries(l1_pv, l2_pv, dist_threshold):
    left_commissure_idx = 1
    right_commissure_idx = 131
    hinge_idx = 449
    corner_vert_idxes = [left_commissure_idx,
                         right_commissure_idx,
                         hinge_idx]

    l1_verts, l1_faces = get_verts_faces_from_pyvista(l1_pv)
    border_vert_idxes = np.where(np.array(igl.is_border_vertex(l1_verts, l1_faces)))[0]
    border_vert_idxes_ordered = get_border_vert_idxes_in_order(l1_faces, left_commissure_idx, reverse=False)
    border_vert_idxes_ordered_list = split_border_vert_idxes_at_corners(border_vert_idxes_ordered, corner_vert_idxes)

    RH_idxes = border_vert_idxes_ordered_list[1]
    LH_idxes = np.flip(border_vert_idxes_ordered_list[2])

    min_length = min(len(RH_idxes), len(LH_idxes))
    RH_idxes = RH_idxes[5:min_length]
    LH_idxes = LH_idxes[5:min_length]

    # dists = np.linalg.norm(l1_pv.points[RH_idxes] - l2_pv.points[LH_idxes], axis=1)
    l1_RH_dists, _, l1_RH_closest_pts = igl.point_mesh_squared_distance(l1_pv.points[RH_idxes], *get_verts_faces_from_pyvista(l2_pv))
    l2_LH_dists, _, l2_LH_closest_pts = igl.point_mesh_squared_distance(l2_pv.points[LH_idxes], *get_verts_faces_from_pyvista(l1_pv))

    RH_idxes_too_close = RH_idxes[l1_RH_dists < dist_threshold/2]
    LH_idxes_too_close = LH_idxes[l2_LH_dists < dist_threshold/2]

    l1_pv_new = l1_pv.copy()
    l2_pv_new = l2_pv.copy()

    if RH_idxes_too_close.sum() > 0:
        l1_RH_mid_points = (l1_pv.points[RH_idxes_too_close] + l1_RH_closest_pts[l1_RH_dists < dist_threshold/2]) / 2
        l2_LH_mid_points = (l2_pv.points[LH_idxes_too_close] + l2_LH_closest_pts[l2_LH_dists < dist_threshold/2]) / 2

        l1_pv_new.points[RH_idxes_too_close] = l1_RH_mid_points + l1_pv.point_normals[RH_idxes_too_close] * dist_threshold/2
        l2_pv_new.points[LH_idxes_too_close] = l2_LH_mid_points + l2_pv.point_normals[LH_idxes_too_close] * dist_threshold / 2

    return l1_pv_new, l2_pv_new

def get_min_dist_verts(verts_choose_from, verts_want_closest_to, return_idx=False):
    min_dist_verts = []
    idx_list = []
    for vert in verts_want_closest_to:
        idx = np.argmin(np.linalg.norm(verts_choose_from - vert, axis=1))
        min_dist_verts.append(verts_choose_from[idx])
        idx_list.append(idx)
    min_dist_verts = np.array(min_dist_verts)

    if return_idx:
        return min_dist_verts, idx_list
    else:
        return min_dist_verts

def get_min_dist_to_border(border_verts, src_verts):
    border_faces = igl.polygon_mesh_to_triangle_mesh_from_list([np.arange(len(border_verts)).tolist()])

    min_dist_verts = []
    for vert in src_verts:
        min_dist_vert = igl.point_mesh_squared_distance(vert, border_verts, border_faces)[2]
        min_dist_verts.append(min_dist_vert)
    min_dist_verts = np.array(min_dist_verts)

    return min_dist_verts

def perform_multiple_splits(exe_path, input_filepath, splitter_filepaths_list, output_filepath, intermediary_filepath=None):
    if len(splitter_filepaths_list)>1:
        for idx, splitter_filepath in enumerate(splitter_filepaths_list):
            if idx == 0:
                run_and_print([exe_path, input_filepath, splitter_filepath, intermediary_filepath])
            elif idx < len(splitter_filepaths_list) - 1:
                run_and_print([exe_path, intermediary_filepath, splitter_filepath, intermediary_filepath])
            else:
                run_and_print([exe_path, intermediary_filepath, splitter_filepath, output_filepath])
    else:
        run_and_print([exe_path, input_filepath, splitter_filepaths_list[0], output_filepath])

    print('done with {}'.format(output_filepath))

def get_split_identifying_pts(geo_filepaths_list, top_or_bot):
    if top_or_bot == 'top':
        HT_pts1, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'hinge_top_path_1' in os.path.basename(f)][0])
        HT_pts2, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'hinge_top_path_2' in os.path.basename(f)][0])
        HT_pts3, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'hinge_top_path_3' in os.path.basename(f)][0])
        CT_pts1, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'top5_commissure_top_path_1' in os.path.basename(f)][0])
        CT_pts2, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'top5_commissure_top_path_2' in os.path.basename(f)][0])
        CT_pts3, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'top5_commissure_top_path_3' in os.path.basename(f)][0])

        split_geo_pts = [
            [HT_pts1, CT_pts1],
            [CT_pts1, HT_pts2],
            [HT_pts2, CT_pts2],
            [CT_pts2, HT_pts3],
            [HT_pts3, CT_pts3],
            [CT_pts3, HT_pts1]
        ]
    elif top_or_bot == 'bot':
        HB_pts1, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'hinge_bot_path_1' in os.path.basename(f)][0])
        HB_pts2, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'hinge_bot_path_2' in os.path.basename(f)][0])
        HB_pts3, _ = igl.read_triangle_mesh([f for f in geo_filepaths_list if 'hinge_bot_path_3' in os.path.basename(f)][0])

        split_geo_pts = [
            [HB_pts1, HB_pts2],
            [HB_pts2, HB_pts3],
            [HB_pts3, HB_pts1]
        ]
    else:
        raise ValueError("2nd argument must be 'top' or 'bot'")

    return split_geo_pts

def get_split_comps(verts, faces, split_identifying_pts):
    verts_comp_assign = igl.vertex_components(faces)
    faces_comp_assign = igl.face_components(faces)

    n_comps = np.unique(verts_comp_assign).size

    verts_list = []
    faces_list = []

    for pts in split_identifying_pts:
        if isinstance(pts, list) and len(pts)>1:
            pts = np.concatenate(pts)

        dist_list = []
        for igl_comp_i in range(n_comps):
            # new_verts = verts[verts_comp_assign == igl_comp_i]

            igl_comp_i_idxes = np.where(verts_comp_assign == igl_comp_i)[0] # converting bool index to int index
            # find which face has a vertex in new_verts, group all faces that has the same comp_assign as that one
            new_faces = faces[faces_comp_assign == faces_comp_assign[np.where(np.any(faces == igl_comp_i_idxes[0], axis=1))[0][0]]]

            dist = igl.point_mesh_squared_distance(pts, verts, new_faces)[0].mean()
            # dist = igl.point_mesh_squared_distance(np.array(pts), np.array(new_verts), np.array(new_faces))[0]
            dist_list.append(dist)

        real_comp_i = np.argmin(np.array(dist_list))

        verts_bool = (verts_comp_assign == real_comp_i)
        comp_i_idxes = np.where(verts_bool)[0]

        mapping = {k: v for k, v in zip(comp_i_idxes, np.arange(len(comp_i_idxes)))}

        new_verts = verts[verts_bool]
        new_faces = faces[faces_comp_assign == faces_comp_assign[np.where(np.any(faces == comp_i_idxes[0], axis=1))[0][0]]]
        new_faces = replace_face_idxes_with_dict(new_faces, mapping)
        # new_faces_orig = new_faces.copy()
        # for k, v in mapping.items():
        #     new_faces[new_faces_orig == k] = v

        verts_list.append(new_verts)
        faces_list.append(new_faces)

    return verts_list, faces_list

def get_border_verts_split_mesh(split_mesh_filepath, corner_verts, save_dir=None, save_prefix="Default"):
    verts, faces = igl.read_triangle_mesh(split_mesh_filepath)
    border_vert_idxes = np.where(np.array(igl.is_border_vertex(verts, faces)))[0]
    border_verts = verts[border_vert_idxes]

    corner_vert_idxes = [np.argmin(np.linalg.norm(corner_vert - border_verts, axis=1)) for corner_vert in corner_verts]
    corner_vert_idxes = border_vert_idxes[corner_vert_idxes]

    border_vert_idxes_ordered = get_border_vert_idxes_in_order(faces, corner_vert_idxes[0], reverse=False)
    border_vert_idxes_ordered_list = split_border_vert_idxes_at_corners(border_vert_idxes_ordered, corner_vert_idxes)

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    if save_dir:
        with open(os.path.join(save_dir, "{}_BoundaryIdxes.txt".format(save_prefix)), 'w') as f:
            f.write("\n".join(" ".join(map(str, x)) for x in border_vert_idxes_ordered_list))
    else:
        return border_vert_idxes_ordered_list

def get_border_verts_template(split_mesh_filepath, corner_vert_idxes, save_dir=None, save_prefix="Default"):
    _, faces = igl.read_triangle_mesh(split_mesh_filepath)

    border_vert_idxes_ordered = get_border_vert_idxes_in_order(faces, corner_vert_idxes[0], reverse=False)
    border_vert_idxes_ordered_list = split_border_vert_idxes_at_corners(border_vert_idxes_ordered, corner_vert_idxes)

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    if save_dir:
        with open(os.path.join(save_dir, "{}_BoundaryIdxes.txt".format(save_prefix)), 'w') as f:
            f.write("\n".join(" ".join(map(str, x)) for x in border_vert_idxes_ordered_list))
    else:
        return border_vert_idxes_ordered_list

def read_BoundaryIdxes_txt(filepath):
    """ each line is a different set of indices (different section of border), space delimiter """
    boundary_idxes = []
    with open(filepath, 'r') as f:
        for line in f:
            boundary_idxes.append(np.array(line.split(' ')).astype(int))

    return boundary_idxes

def apply_vtkSmoothPolyDataFilter(verts, faces, n_iter=100, relaxation_factor=0.01):
    '''
    http://www.vtk.org/doc/nightly/html/classvtkSmoothPolyDataFilter.html
    '''

    def mkVtkIdList(it):
        """
        :param it: A python iterable.
        :return: A vtkIdList
        """
        vil = vtk.vtkIdList()
        for i in it:
            vil.InsertNextId(int(i))
        return vil

    # converting verts and faces to vtkPolyData object
    vtk_mesh = vtk.vtkPolyData()
    points = vtk.vtkPoints()
    polys = vtk.vtkCellArray()

    for idx, vert in enumerate(verts):
        points.InsertPoint(idx, vert)
    for face in faces:
        polys.InsertNextCell(mkVtkIdList(face))

    vtk_mesh.SetPoints(points)
    vtk_mesh.SetPolys(polys)

    # setting and applying the filter
    smooth_filter = vtk.vtkSmoothPolyDataFilter()
    smooth_filter.SetInputData(vtk_mesh)
    smooth_filter.SetNumberOfIterations(n_iter)
    smooth_filter.SetRelaxationFactor(relaxation_factor)
    smooth_filter.FeatureEdgeSmoothingOff()
    # smooth_filter.FeatureEdgeSmoothingOn()
    smooth_filter.BoundarySmoothingOff()
    # smooth_filter.BoundarySmoothingOn()
    smooth_filter.Update()
    vtk_mesh_smooth = smooth_filter.GetOutput()

    # converting vtkPolyData object back to verts and faces
    verts_smooth = vtk.util.numpy_support.vtk_to_numpy(vtk_mesh_smooth.GetPoints().GetData())
    faces_smooth = vtk.util.numpy_support.vtk_to_numpy(vtk_mesh_smooth.GetPolys().GetData()).reshape(-1, 4)[:, 1:]

    return verts_smooth, faces_smooth

def get_top_commissure_cut_vert(aw_verts, aw_faces, border_verts, commissure_pt, cut_path_pts):
    # from path_pts, get smallest dist pts to top or bottom surface of aortic wall
    border_cover_faces = igl.polygon_mesh_to_triangle_mesh(np.arange(border_verts.shape[0])[np.newaxis])
    border_cover_mesh = utils_sp.mesh_to_pyvista_PolyData(border_verts, border_cover_faces)
    smallest_dists = igl.point_mesh_squared_distance(cut_path_pts, *get_verts_faces_from_pyvista(border_cover_mesh))[0]

    # 2 smallest dist points candidates b/c of how we defined cutting plane - choose one closest in geo dist to commissure pt
    commissure_top_candidates = cut_path_pts[np.argpartition(smallest_dists, 2)[:2]] # get two smallest values
    idxes_src = get_min_dist_verts(border_verts, commissure_pt[np.newaxis], return_idx=True)[1]
    idxes_tgt = get_min_dist_verts(border_verts, commissure_top_candidates, return_idx=True)[1]
    dists = igl.exact_geodesic(aw_verts, aw_faces, np.array(idxes_src), np.array(idxes_tgt))
    top_commissure_cut_vert = commissure_top_candidates[np.argmin(dists)]

    return top_commissure_cut_vert

def split_list(input_list, split_idxes):
    new_list = []
    prev_idx = 0
    for split_idx in split_idxes:
        new_list.append(input_list[prev_idx:split_idx])
        prev_idx = split_idx
    return new_list

def get_sep_components_from_all_verts_all_faces(all_verts, all_faces, idx_tracks, verts_len_list, faces_len_list):
    """ inputs from: _,_,idx_tracks = igl.remove_duplicates(all_verts, all_faces) """
    idx_track_list = np.split(idx_tracks, np.cumsum(verts_len_list)[:-1]) # shape [9141, 985, 985, 985]
    verts_new_list = [all_verts[idx_track] for idx_track in idx_track_list]

    faces_new_list = []
    faces_list = split_list(all_faces, np.cumsum(faces_len_list))
    cum_faces_len = 0
    for faces, idx_track in zip(faces_list, idx_track_list):
        replace_dict = {k: v for k, v in zip(idx_track, cum_faces_len + np.arange(len(idx_track)))}
        faces_new = replace_face_idxes_with_dict(faces, replace_dict)
        faces_new_list.append([[idx - cum_faces_len for idx in face_new] for face_new in faces_new])
        # faces_new_list.append(faces_new - cum_faces_len) # only works for np, not list of lists for mixed tri/quad elements
        cum_faces_len += len(faces)

    return verts_new_list, faces_new_list

def get_sep_components_from_all_verts_all_faces_torch(all_verts, all_faces, idx_tracks, verts_len_list, faces_len_list):
    """
    inputs from: _,_,idx_tracks = igl.remove_duplicates(all_verts, all_faces)
    all_verts: torch.tensor, [n_batch, n_verts, n_dim]
    all_faces: torch.tensor, [n_batch, n_faces (3), n_verts_per_face]
    """

    def size_splits(tensor, split_sizes, dim=0):
        """Splits the tensor according to chunks of split_sizes.

        Arguments:
            tensor (Tensor): tensor to split.
            split_sizes (list(int)): sizes of chunks
            dim (int): dimension along which to split the tensor.
        """
        if dim < 0:
            dim += tensor.dim()

        dim_size = tensor.size(dim)
        if dim_size != torch.sum(torch.Tensor(split_sizes)):
            raise KeyError("Sum of split sizes exceeds tensor dim")

        splits = torch.cumsum(torch.Tensor([0] + split_sizes), dim=0)[:-1]

        return list(tensor.narrow(int(dim), int(start), int(length))
            for start, length in zip(splits, split_sizes))

    idx_track_list = size_splits(torch.tensor(idx_tracks, dtype=int), verts_len_list) # e.g. shape [9141, 985, 985, 985]
    verts_new_list = [all_verts[:,idx_track,:] for idx_track in idx_track_list]

    faces_split_list = size_splits(all_faces, faces_len_list, dim=1)
    face_idx_offset_list = [0, *(list(np.cumsum(verts_len_list))[:-1])]

    faces_new_list = []
    cum_faces_len = 0
    for faces, idx_track in zip(faces_split_list, idx_track_list):
        replace_dict = {k: v for k, v in zip(idx_track, cum_faces_len + np.arange(len(idx_track)))}
        faces_new = replace_face_idxes_with_dict_torch(faces, replace_dict)
        faces_new_list.append(faces_new - cum_faces_len) # only works for np, not list of lists for mixed tri/quad elements
        cum_faces_len += len(faces)

    # remove batch dimension (assuming n_batch=1)
    output_verts_new_list = [verts_new.squeeze(0) for verts_new in verts_new_list]
    output_faces_new_list = [faces_new.squeeze(0) for faces_new in faces_new_list]

    return output_verts_new_list, output_faces_new_list

def find_neighbor_nodes(faces, node_idx):
    """Pass the index of the node in question.
    Returns the vertex indices of the vertices connected with that node."""
    neighbor_faces = np.vstack([face for face in faces if node_idx in face])
    connected = np.unique(neighbor_faces.ravel()) # get unqiue node indices
    return np.delete(connected, np.argwhere(connected == node_idx)) # delete original node_idx

def find_neighbor_face_idxes_by_edge(faces, edge):
    return np.where(np.all(faces == edge[0], faces == edge[1]))

def replace_face_idxes_with_dict(faces, replace_dict):
    if isinstance(faces, list):
        faces_new = []
        for face in faces:
            new_face = [replace_dict[orig_idx] for orig_idx in face]
            faces_new.append(new_face)
    elif isinstance(faces, torch.Tensor):
        faces_new = faces.clone()
        for key, val in replace_dict.items():
            faces_new[faces==key] = int(val)
    elif isinstance(faces, np.ndarray):
        faces_new = faces.copy()
        for key, val in replace_dict.items():
            faces_new[faces==key] = int(val)
    return faces_new

def replace_face_idxes_with_dict_torch(faces, replace_dict):
    faces_new = faces.clone()
    for key, val in replace_dict.items():
        faces_new[faces==key] = int(val)
    return faces_new

def load_inp_as_pv(filepath, return_tri_pv=False):
    store_verts = False
    store_faces_2d = False
    store_faces_3d = False

    with open(filepath, 'r') as fstream:
        verts_dict = {}
        faces_2d_list = []
        faces_3d_list = []

        line_hold = ''

        for line_idx, line_orig in enumerate(fstream):
            line = line_orig.rstrip('\n')

            """ this is to take care of long face_idxes, sometimes there is \n after some amount of indices """
            if line[-1] == ',':
                line_hold = line
                continue
            else:
                line = line_hold + line
                line_hold = ''

            line_parse = line.split('*')

            if len(line_parse) > 1:
                if line_parse[1] == 'NODE':
                    store_verts = True
                    continue

                if 'ELEMENT' in line_parse[1]:
                    if line.split(',')[1] == 'TYPE=S3':
                        store_faces_2d = True
                        n_elem = 3
                        continue

                    elif line.split(',')[1] == 'TYPE=S4R' or line.split(',')[1] == 'TYPE=S4':
                        store_faces_2d = True
                        n_elem = 4
                        continue

                    elif line.split(',')[1] == 'TYPE=C3D8R':
                        store_faces_3d = True
                        n_elem = 8
                        continue

            if store_verts:
                if len(line_parse) == 1: # to turn off store_verts when we hit another asterisk
                    line_parse2 = line.split(',  ')
                    """
                    line_parse2[0]: vert index given by .inp
                    we want to replace those with our own index - just the order of vertex listing np.arange(len)
                    fixed indexing line_parse2[1:4] b/c always 3D points
                    """
                    verts_dict[int(line_parse2[0])] = line_parse2[1:4]
                else:
                    store_verts = False

            if store_faces_2d: # to turn off store_faces_2d when we hit another asterisk
                if len(line_parse) == 1:
                    line_parse2 = line.split(',     ')
                    faces_2d_list.append(np.array(line_parse2[1 : n_elem+1]).astype(int).tolist())
                else:
                    store_faces_2d = False

            if store_faces_3d:
                if len(line_parse) == 1: # to turn off store_faces_3d when we hit another asterisk
                    line_parse2 = line.split(',     ')
                    faces_3d_list.append(np.array(line_parse2[1 : n_elem+1]).astype(int).tolist())
                else:
                    store_faces_3d = False

    """ we want to get rid of verts that don't contribute to faces (probably free-floating nodes in hypermesh) """
    all_face_idxes = np.unique(np.hstack(faces_2d_list + faces_3d_list))
    verts_for_faces_dict = {key: value for key, value in verts_dict.items() if key in all_face_idxes}

    """ replace .inp indices with vertex order indices """
    replace_dict = {idx1: idx2 for idx1, idx2 in zip(list(verts_for_faces_dict.keys()), np.arange(len(verts_for_faces_dict)))}
    faces_2d_idx_changed = replace_face_idxes_with_dict(faces_2d_list, replace_dict)
    faces_3d_idx_changed = replace_face_idxes_with_dict(faces_3d_list, replace_dict)

    if len(faces_2d_idx_changed) > 0:
        mesh_2d_pv = utils_sp.mesh_to_pyvista_PolyData(np.array(list(verts_for_faces_dict.values())).astype(float), faces_2d_idx_changed)
    else:
        mesh_2d_pv = None

    if len(faces_3d_idx_changed) > 0:
        mesh_3d_pv = mesh_to_pyvista_UnstructuredGrid(np.array(list(verts_for_faces_dict.values())).astype(float), faces_3d_idx_changed)
    else:
        mesh_3d_pv = None

    if mesh_2d_pv and mesh_3d_pv:
        return mesh_2d_pv, mesh_3d_pv
    elif mesh_2d_pv:
        if return_tri_pv:
            tri_faces = split_quad_to_2_tri_mesh(faces_2d_idx_changed)
            mesh_2d_pv_tri = utils_sp.mesh_to_pyvista_PolyData(mesh_2d_pv.points, tri_faces)
            return mesh_2d_pv, mesh_2d_pv_tri
        else: mesh_2d_pv
    elif mesh_3d_pv:
        return mesh_3d_pv
    else:
        return None

def extract_single_surf_from_3d_elem(mesh_3d_pv, base_surf=True):
    verts, faces_3d = get_verts_faces_from_pyvista(mesh_3d_pv)
    if base_surf:
        face_surf = faces_3d[:,:4]
    else:
        face_surf = faces_3d[:,4:]

    verts_dict = {idx: vert for idx, vert in enumerate(verts)}

    """ remove verts that don't contribute to surface faces and update face_idxes with new vert indices """
    all_face_idxes = np.unique(np.hstack(face_surf))
    verts_for_faces_dict = {key: value for key, value in verts_dict.items() if key in all_face_idxes}

    replace_dict = {idx1: idx2 for idx1, idx2 in zip(list(verts_for_faces_dict.keys()), np.arange(len(verts_for_faces_dict)))}
    faces_idx_changed = replace_face_idxes_with_dict(face_surf, replace_dict)

    mesh_2d_pv = utils_sp.mesh_to_pyvista_PolyData(np.array(list(verts_for_faces_dict.values())).astype(float), faces_idx_changed)

    return mesh_2d_pv

def remove_duplicates_DP(verts, faces, eps):
    """main difference with igl.remove_duplicates is just that I need flexibility with mixed tri/quad meshes"""
    faces_tri = split_quad_to_2_tri_mesh(faces)
    new_verts, _, idx_tracks = igl.remove_duplicates(verts, faces_tri, eps)
    replace_dict = {k: v for k, v in zip(np.arange(len(idx_tracks)), idx_tracks)}
    new_faces = replace_face_idxes_with_dict(faces, replace_dict)

    return new_verts, new_faces, idx_tracks

def mesh_to_pyvista_UnstructuredGrid(verts, faces):
    """ only compatible with tetrahedron, hexahedron (8 verts, flexible rectangular prism) and wedge (6 verts, flexible triangular prism) for now """
    faces_pv = []
    cell_types = []
    for face in faces:
        faces_pv += ([len(face)] + list(face))
        if len(face) == 4:
            cell_types.append(vtk.VTK_TETRA)
        elif len(face) == 6:
            cell_types.append(vtk.VTK_WEDGE)
        elif len(face) == 8:
            cell_types.append(vtk.VTK_HEXAHEDRON)
        elif len(face) == 15:
            cell_types.append(vtk.VTK_QUADRATIC_WEDGE)
        elif len(face) == 20:
            cell_types.append(vtk.VTK_QUADRATIC_HEXAHEDRON)
        else:
            raise ValueError('faces must have either 4, 6, or 8 indices for each cell')

    faces_pv = np.array(faces_pv).astype(int)
    cell_types = np.array(cell_types).astype(np.uint8)

    return pv.UnstructuredGrid(faces_pv, cell_types, verts)

def unstructured_to_polydata(unstructured_pv):
    return utils_sp.mesh_to_pyvista_PolyData(*get_verts_faces_from_pyvista(unstructured_pv))

def bring_verts_together(mesh_pv1_list, mesh_pv2_list, vert_idxes1, vert_idxes2):
    for mesh_pv1, mesh_pv2 in zip(mesh_pv1_list, mesh_pv2_list):
        new_pts = (mesh_pv1.points[vert_idxes1] + mesh_pv2.points[vert_idxes2])/2
        mesh_pv1.points[vert_idxes1] = new_pts
        mesh_pv2.points[vert_idxes2] = new_pts
    # no need to return anything b/c it should change mesh_pv1 and mesh_pv2 by reference

def merge_pv_meshes(all_pv_list, tolerance=1e-1, return_sep_one_verts=False, return_sep_verts_list=False, return_stuff_for_sep=False):
    all_verts = []
    all_faces = []
    verts_len_list = []
    faces_len_list = []
    cum_verts_len = 0
    for mesh_pv in all_pv_list:
        verts, faces = get_verts_faces_from_pyvista(mesh_pv)
        verts_len_list.append(len(verts))
        faces_len_list.append(len(faces))
        all_verts.append(verts)
        all_faces += [[f + cum_verts_len for f in face] for face in faces]
        cum_verts_len += len(verts)

    all_verts = np.concatenate(all_verts, axis=0)
    all_verts, all_faces, idx_tracks = remove_duplicates_DP(all_verts, all_faces, tolerance)
    all_combined_pv = utils_sp.mesh_to_pyvista_PolyData(all_verts, all_faces)

    if return_sep_one_verts:
        faces_new_list = split_list(all_faces, np.cumsum(faces_len_list))
        return all_combined_pv, faces_new_list
    elif return_sep_verts_list:
         verts_new_list, faces_new_list = get_sep_components_from_all_verts_all_faces(all_verts, all_faces, idx_tracks, verts_len_list, faces_len_list)
         return verts_new_list, faces_new_list
    elif return_stuff_for_sep:
        return all_verts, all_faces, idx_tracks, verts_len_list, faces_len_list
    else:
        return all_combined_pv
